package types

const (
	PathV1Sign            = "/v1/sign"
	PathHealthz           = "/healthz"
	PathRoot              = "/"
	PathAssetsPrefix      = "/assets/"
	PathApp               = "/app"
	PathAppPrefix         = "/app/"
	PathAdmin             = "/admin"
	PathAdminPrefix       = "/admin/"
	PathAdminSnapshot     = "/admin/snapshot"
	PathAdminLeasesPrefix = "/admin/leases/"
	PathAdminSettings     = "/admin/settings"
	PathAdminIPsPrefix    = "/admin/ips/"
	PathAuthPrefix        = "/auth/"
	PathAuthSession       = "/auth/session"
	PathAuthLogout        = "/auth/logout"
	PathAuthLeases        = "/auth/leases"
	PathAuthSIWEChallenge = "/auth/siwe/challenge"
	PathAuthSIWEVerify    = "/auth/siwe/verify"
	PathInstallShell      = "/install.sh"
	PathInstallPowerShell = "/install.ps1"
	PathInstallBinPrefix  = "/install/bin/"

	PathTunnelStatus    = "/tunnel/status"
	PathThumbnailPrefix = "/thumbnail/"

	PathSDKPrefix            = "/sdk/"
	PathSDKDomain            = "/sdk/domain"
	PathSDKRegisterChallenge = "/sdk/register/challenge"
	PathSDKRegister          = "/sdk/register"
	PathSDKRenew             = "/sdk/renew"
	PathSDKUnregister        = "/sdk/unregister"
	PathSDKHop               = "/sdk/hop"
	PathSDKConnect           = "/sdk/connect"
	PathDiscovery            = "/discovery"
	PathDiscoveryAnnounce    = "/discovery/announce"
)
